/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tic_tac_toe;

import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalButtonUI;

/**
 *
 * @author kali-i
 */
public class Dashboard extends javax.swing.JFrame {

    String player="X";
    boolean a=false,a1=false,a2=false,a3=false,a4=false,a5=false,a6=false,a7=false,a8=false;
   public Dashboard() {
        initComponents();
    }
    
    public void changePlayer(String data){
        if(data=="X")
        player="O";
        else
        player="X";    
    }
    public void UpdateUI(String data,JButton b){
        if(data.contentEquals("X")){
            b.setLabel("X");
            b.setFont(new Font("Cantarell Extra Bold", Font.BOLD, 70));
            b.setForeground(Color.blue);            
             b.setUI(new MetalButtonUI() {
            protected Color getDisabledTextColor() {
             return Color.blue;
            }
            });
            b.setEnabled(false);
            changePlayer("X");
            checkWinner(data);
        }else{
            b.setLabel("O");
            b.setFont(new Font("Cantarell Extra Bold", Font.BOLD, 70));
            b.setForeground(Color.red);
            b.setUI(new MetalButtonUI() {
            protected Color getDisabledTextColor() {
        return Color.red;
            }
            });
            b.setEnabled(false);   
            changePlayer("O");
            checkWinner(data);
           
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new ImagePanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jButton10.setText("jButton10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 206, 132));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIC TAC TOE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 10, 250, 73);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"Make your move and claim your spot on the Tic Tac Toe grid!\"");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 100, 570, 44);

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 230, 100);

        jButton1.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 70)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 150, 111, 92);

        jButton2.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 70)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 150, 111, 92);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 150, 111, 92);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(300, 270, 111, 92);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(440, 270, 111, 92);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(580, 270, 111, 92);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(300, 390, 111, 92);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(440, 390, 111, 92);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(580, 390, 111, 92);

        jLabel5.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Player O  :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 290, 140, 30);

        jLabel6.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 290, 100, 30);

        jLabel7.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Player X  :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 230, 140, 30);

        jLabel9.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Score");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 170, 100, 30);

        jLabel10.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 230, 100, 30);

        jButton11.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 204, 51));
        jButton11.setText("Reset");
        jButton11.setVisible(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(780, 150, 120, 60);

        jButton12.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 0));
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(20, 390, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.UpdateUI(player, this.jButton4);
        a3=true;
        checkDraw();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.UpdateUI(player, this.jButton1);
        a=true;
        checkDraw();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  this.UpdateUI(player, this.jButton2);
  a1=true;
   checkDraw();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  this.UpdateUI(player, this.jButton3);
a2=true;
 checkDraw();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  this.UpdateUI(player, this.jButton5);
  a4=true;
   checkDraw();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  this.UpdateUI(player, this.jButton6);
a5=true;
 checkDraw();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  this.UpdateUI(player, this.jButton7);
a6=true;
 checkDraw();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
  this.UpdateUI(player, this.jButton8);
a7=true;
 checkDraw();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
  this.UpdateUI(player, this.jButton9);
a8=true;
 checkDraw();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.jButton11.setVisible(false);
        a=false;a1=false;a2=false;a3=false;a4=false;a5=false;a6=false;a7=false;a8=false;
        player="X";
        enableAll();
        this.jButton1.setText("");
        this.jButton2.setText("");
        this.jButton3.setText("");
        this.jButton4.setText("");
        this.jButton5.setText("");
        this.jButton6.setText("");
        this.jButton7.setText("");
        this.jButton8.setText("");
        this.jButton9.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    public void checkDraw(){
        if(a==true&&a1==true&&a2==true&&a3==true&&a4==true&&a5==true&&a6==true&&a7==true&&a8==true){
            this.jButton11.setVisible(true);
        }
    }
    
    public void checkWinner(String player){
      String x=this.jLabel10.getText();
      String o=this.jLabel6.getText();
      int x1=Integer.parseInt(x);
      int o1=Integer.parseInt(o);
      if(this.jButton1.getText().contentEquals(player)&&this.jButton2.getText().contentEquals(player)&&this.jButton3.getText().contentEquals(player)){
       if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
        disableAll();
      }
      
      else if(this.jButton4.getText().contentEquals(player)&&this.jButton5.getText().contentEquals(player)&&this.jButton6.getText().contentEquals(player)){
 if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
      disableAll();
      }
      else   if(this.jButton7.getText().contentEquals(player)&&this.jButton8.getText().contentEquals(player)&&this.jButton9.getText().contentEquals(player)){
      if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
  disableAll();
      }
   else   if(this.jButton1.getText().contentEquals(player)&&this.jButton5.getText().contentEquals(player)&&this.jButton9.getText().contentEquals(player)){
      if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
   disableAll();  
   }
      
     else if(this.jButton1.getText().contentEquals(player)&&this.jButton4.getText().contentEquals(player)&&this.jButton7.getText().contentEquals(player)){
       if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
   disableAll();
     }

    else if(this.jButton2.getText().contentEquals(player)&&this.jButton5.getText().contentEquals(player)&&this.jButton8.getText().contentEquals(player)){
       if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
    disableAll(); 
    }
      
     else if(this.jButton3.getText().contentEquals(player)&&this.jButton6.getText().contentEquals(player)&&this.jButton9.getText().contentEquals(player)){
       if(player.contentEquals("X"))   
       x1++;
       else
       o1++;
      System.out.print(player+" is winner");
    disableAll();
     }
      this.jLabel10.setText(String.valueOf(x1));
      this.jLabel6.setText(String.valueOf(o1));
      
    }
    
    public void disableAll(){
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jButton6.setEnabled(false);
        this.jButton7.setEnabled(false);
        this.jButton8.setEnabled(false);
        this.jButton9.setEnabled(false);
      this.jButton11.setVisible(true);
    }
    public void enableAll(){
        this.jButton1.setEnabled(true);
        this.jButton2.setEnabled(true);
        this.jButton3.setEnabled(true);
        this.jButton4.setEnabled(true);
        this.jButton5.setEnabled(true);
        this.jButton6.setEnabled(true);
        this.jButton7.setEnabled(true);
        this.jButton8.setEnabled(true);
        this.jButton9.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
